# -*- coding: utf-8 -*-
"""STONE PAPER SCISSORS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bVeG6hcI711DPbx20Iz8NvQ0Q6N-dDpD
"""

import random

user_score = 0
computer_score = 0

while True:
    print("Welcome to Rock, Paper, Scissors!")
    print("Choose your move:")
    print("1. Rock")
    print("2. Paper")
    print("3. Scissors")

    user_choice = int(input("Enter the number corresponding to your choice: "))
    if user_choice < 1 or user_choice > 3:
        print("Invalid choice. Please choose a valid option.")
        continue

    choices = ["Rock", "Paper", "Scissors"]
    computer_choice = random.choice(choices)

    print(f"You chose: {choices[user_choice-1]}")
    print(f"Computer chose: {computer_choice}")

    if user_choice == 1 and computer_choice == "Scissors" or user_choice == 2 and computer_choice == "Rock" or user_choice == 3 and computer_choice == "Paper":
        print("Yahoo!You win!")
        user_score += 1
    elif user_choice == 1 and computer_choice == "Paper" or user_choice == 2 and computer_choice == "Scissors" or user_choice == 3 and computer_choice == "Rock":
        print("Oopss!Computer wins!")
        computer_score += 1
    else:
        print("It's a tie!")

    print(f"Your Score: {user_score} - Computer Score: {computer_score}")

    play_again = input("Do you want to play again? (yes/no): ")
    if play_again.lower() != "yes":
        break